### ISSUE TITLE
TypeError on isValid

### ISSUE THREAD

**Issue by stoplion** [thedersen/backbone.validation#117]
_EDIT_

I cant get this plugin to work. 
I've read the documentation up and down. 
Using BB 1.0.0.

```
class window.Models.SearchQuery extends Backbone.Model

   defaults:
       city: ''
       keywords: ''
       lat: ''
       long: ''
       location: ''
       performed_at: ''
       region: ''


   validation:
       keywords:
           required: true
           pattern: 'number'
       location:
           required: true
           pattern: 'number'
```

**With Mixin set..**

```
 //calling this in my routers initialize method..
 _.extend(Backbone.Model.prototype, Backbone.Validation.mixin)

//Then in Chrome dev Tools...
m = new App.Models.SearchQuery({validate:true})
m.set({'location': 'ewf3ef3ref3rf'})
m.isValid(true)
```

TypeError: Cannot call method 'call' of undefined
