### ISSUE TITLE
forceUpdate: true bug?

### ISSUE THREAD

**Issue by TimBrunsmo** [thedersen/backbone.validation#44]
I don't know if it is a bug or if I'm doing something wrong.

I have an model with 4 attributes and validations:

```
class gh.Models.SomeModel extends Backbone.Model
  defaults:
    attr1: ""
    attr2: ""
    attr3: ""
    attr4: ""

  validation:
    attr1:
      pattern: 'number'
    attr2:
      pattern: 'number'
    attr3:
      pattern: 'number'
    attr4:
      pattern: 'number'

end
```

Then I'm binding validation in a view:

```
class gh.Views.SomeView extends Backbone.View
  render: =>
    # omitted
    Backbone.Validation.bind @, { forceUpdate: true }
end
```

The problem I'm having is that even though I used `forceUpdate: true` all attributes is being validated on change.

Shouldn't forceUpdate "suppress" validation on set for this view?

I want to validate the model manually on save.
