### ISSUE TITLE
Probably BUG with preValidate() and null value

### ISSUE THREAD

**Issue by starkovv** [thedersen/backbone.validation#80]
Have a model:

```
module.exports = class Session extends Model

  urlRoot: '/sessions'
  idAttribute: 'user_id'

  defaults:
    authenticated: null

  validation:
    authenticated:
      required: false
```

Have a test:

```
...
  it 'is valid when not presented', ->
    @session.set('authenticated', null)
    expect(@session.preValidate('authenticated', null)).to.equal('')
...
```

When I run test it raises error:

```
expected false to equal ''
```

For some reason if I do preValidate() with `null` attribute value it returns `false` instead of `undefined` as described in docs.

Check this out please.
